version: "3.8"

services:
  web:
    build: .
    ports:
      - "8080:3000"    # Mapeia a porta 3000 do contêiner para a porta 8080 do host
    depends_on:
      - db             # Garante que o serviço db seja iniciado antes do web
    environment:
      - DB_HOST=db     # Host para conexão com o MySQL, corresponde ao nome do serviço "db"
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # Configura a senha do usuário root
      MYSQL_DATABASE: ${DB_NAME}          # Cria o banco de dados automaticamente
      MYSQL_USER: ${DB_USER}              # Cria um usuário regular (não-root)
      MYSQL_PASSWORD: ${DB_PASSWORD}      # Senha para o usuário regular
    volumes:
      - db-data:/var/lib/mysql            # Volume para persistência dos dados do MySQL
    networks:
      - app-network

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
